version: '3.1'
services:
  db:
    image: postgres:13
    container_name: dbBotiga
    environment:  
      - POSTGRES_DB=ITIC_DB_Botiga
      - POSTGRES_PASSWORD=ITIC
      - POSTGRES_USER=ITIC
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4Botiga
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2023_joel.ghanem@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: