# Generated by Django 5.0.4 on 2024-05-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('tarjeta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FakeCarreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producte', models.CharField(max_length=255)),
                ('preu', models.IntegerField()),
                ('quantitat', models.IntegerField()),
                ('pagat', models.BooleanField(default=False)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagaments.usuari')),
            ],
        ),
    ]
