# Generated by Django 5.0.4 on 2024-04-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('preu', models.FloatField()),
                ('stock', models.IntegerField()),
                ('descripcio', models.CharField(max_length=255)),
                ('pes', models.FloatField()),
                ('subcategoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cataleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('id_producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.producte')),
            ],
        ),
    ]
